### ISSUE TITLE
Extension Manager shows that markdowku version 2017-02-19 is available, update fails

### ISSUE THREAD

**Issue by serankua** [arapat/markdowku#3]
Extension Manager cannot update from a previous version of markdowku (2016-01-19 in my case) to the supposedly latest version (2017-02-19).

As per https://www.dokuwiki.org/plugin:extension

"For the update process to work properly it is necessary that the date “Last updated on” in the Dokuwiki Extension repository equals the date in the file plugin.info.txt for plugins and template.info.txt for templates in the source tarbal/zipfile. If this is not the case: the update will not take place or the “Update” signal persists."

I checked the source zip file in the Dokuwiki Extension repository, and the file plugin.info.txt has a date of 2016-01-19. After looking at the repository, there haven't been any commits since version 2016-01-19. The people in charge of the Dokuwiki plugin repository should be contacted to fix the issue.

**Comment by Xuanwo** [comment]
The same.

**Comment by arapat** [comment]
This repository should not be pointed from dokuwiki extension page because it is not to take over the project but a temporary fix to the PHP 7 incompatibility issue. Please report the issue to the author.

I have fixed the URLs on https://www.dokuwiki.org/plugin:markdowku. Now they point to the author's page.
